### ISSUE TITLE
Create Wiki describing HPC use (Jupyter, private queue, etc)

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/mind-reading#11]

**Comment by georgebuzzell** [comment]
@CamachoBry @kiaraafarias @cma0232 I need to create the wiki entry for this, but to keep things moving for now, please see below:

How to use Jupiter:
go to hpcgui.fiu.edu and launch panther desktop
![image](https://user-images.githubusercontent.com/71228105/112245473-53a70500-8c27-11eb-9032-19eea8893ebf.png)

once desktop launched, open a terminal and load conda, then jupyter
![image](https://user-images.githubusercontent.com/71228105/112245489-5d306d00-8c27-11eb-9352-8941ad7ac994.png)


use conda environment for our scripts instead of pip (no version control): http://ircc.fiu.edu/custom-environments-and-package-installation-r-and-python/

this is how to specify slurm script. note private cue at top. we should always say medium, and then always specify one of the medium machines.
![image](https://user-images.githubusercontent.com/71228105/112245511-69b4c580-8c27-11eb-99ea-3fc1ae654c23.png)

**Comment by jessb0t** [comment]
I just created a pull request on the wiki repo to push this content to the wiki!

**Comment by georgebuzzell** [comment]
@jessb0t Wow; thank you SO MUCH! Checking the PR now!!
